[tool.poetry]
name = "ductile-ui"
version = "0.1.0"
description = "A library provides interactive ui for discord.py"
authors = ["sushi-chaaaan <mail@sushichan.live>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "ductile", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
discord-py = "^2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
